version: "3.9"
services:
  bot:
    build:
      context: .
    container_name: bot
    restart: always
    environment:
      BOT_TELEGRAM_TOKEN: "6113934108:AAGAazyc4__S7Uq9lSr6X9UP8yg1Jc33y6U"
      BOT_CLIENT_TIME_TOKEN: "5TEOC6R12XJX"
      BOT_CLIENT_TIME_URL: "https://api.timezonedb.com/v2.1/get-time-zone"
      BOT_POSTGRES_NAME: "bot"
      BOT_POSTGRES_HOST: "db"
      BOT_POSTGRES_PORT: 5432
      BOT_POSTGRES_USER: "user"
      BOT_POSTGRES_PASSWORD: "password"
      BOT_MIGRATIONS_SOURCE_URL: "file://migrations"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "bot"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
